sonar.verbose=true
sonar.organization=valax01-key1
sonar.projectKey=sathishr53_tweet-trend12
sonar.projectName=tweet-trend12
sonar.language=java
sonar.sourceEncoding=UTF-8
sonar.sources= .
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=/target/site/jacoco/jacoco.xml